version: "3.1"

services:
  app:
    build: ./app
    restart: always
    container_name: AplColluding_api
    ports:
      - 5000:5000
    networks:
      - api-net
#    volumes:
#    - './apk_files:/ApkColluding/apk_files/'
#    - './compiled_apk:/ApkColluding/compiled_apk/'
  client:
    image: nginx:alpine
    container_name: ApkColluding_web
    ports:
      - 80:80
    volumes:
      - ./client/html:/usr/share/nginx/html
      - ./client/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-net

networks:
  api-net:
    driver: bridge