version: "3.1"

services:
  app:
    build: ./app
    restart: always
    container_name: AplColluding_api
    ports:
      - 5000:5000
  client:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./src:/usr/share/nginx/html